compatibility_date = "2026-08-28"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
main = "src/index.js"

[[kv_namespaces]]
binding = "MAILBOX"

[assets]
directory = "./public"
binding = "ASSETS"
